name: Simple CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker permissions
      run: |
        sudo chmod 666 /var/run/docker.sock
        sudo usermod -aG docker $USER
    
    - name: Clean up Docker
      run: |
        sudo docker system prune -af --volumes
    
    - name: Build and run Docker container
      run: |
        # 이전 컨테이너 중지 및 제거
        sudo docker stop cloudrag-app || true
        sudo docker rm cloudrag-app || true
        
        # 새 이미지 빌드
        sudo docker build -t cloudrag-app .
        
        # 새 컨테이너 실행
        sudo docker run -d \
          --name cloudrag-app \
          -p 8000:8000 \
          -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          -e TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }} \
          cloudrag-app
